services:
  mongo:
    # Use mongodb community server image. UBI (Universal Base Image) is a minimal base image that is based on Red Hat Universal Base Image (UBI).
    image: mongodb/mongodb-community-server:8.0.3-ubi9
    container_name: mongodb
    restart: always
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=
      - MONGODB_INITDB_ROOT_PASSWORD=

  mongo-init:
    image: mongodb/mongodb-community-server:8.0.3-ubi9
    depends_on:
      - mongo
    entrypoint: >
      bash -c '
        echo "Waiting for MongoDB to be ready...";
        until mongosh --host mongo --eval "db.adminCommand(\"ping\")" --quiet; do
          sleep 1;
        done;
        echo "MongoDB is up. Running replica set initiation...";
        mongosh --host mongo --quiet --eval "
          try {
            if (!rs.status().ok) {
              throw new Error();
            }
          } catch (e) {
            rs.initiate({
              _id: \"rs0\",
              members: [{ _id: 0, host: \"mongo:27017\" }]
            });
          }"
      '
    restart: "no"
volumes:
  mongo-data:
    driver: local
